cloudnative-pg/charts

charts/cnpg-sandbox/README.md
charts/cnpg-sandbox/values.schema.json
charts/cnpg-sandbox/values.yaml

The chart cnpg-sandbox was still setting monitoring queries via environment variables, which is not required anymore given that now the source `cloudnative-pg` chart is shipping that configmap by default. Moreover, the current setting was wrong as the name was not the actual name of the now default configmap.
Closes #51

fix(cnpg-sandbox): removing explicit reference to monitoring queries

---

.github/workflows/lint.yml

Given that we removed cnpg-sanbox chart from this repo, we also need to remove related steps from the pipelines.
Signed-off-by: Philippe Scorsolini <p.scorsolini@gmail.com>

ci: remove cnpg-sandbox from lint pipeline

---

charts/cloudnative-pg/README.md
charts/cloudnative-pg/templates/deployment.yaml
charts/cloudnative-pg/values.schema.json
charts/cloudnative-pg/values.yaml

Fix: #64 
This PR adds the capability to define a `priorityClassName` in the CNPG deployment. Since the controller is mission critical workload by defining a priorityClassName we can ensure that controller gets enough resources defined in the `priortiyClass`.

Add PriorityClassName to the CNPG Controller

---

charts/cloudnative-pg/README.md
charts/cloudnative-pg/templates/deployment.yaml
charts/cloudnative-pg/values.schema.json
charts/cloudnative-pg/values.yaml

Set the securityContext at the container level in values file. To install the operator on openshift with the 'restricted' scc, you need to choose a user and an fsgroup allowed by the namespace. User 10001 will give an error.

add containerSecurityContext to Values file

---

charts/cloudnative-pg/templates/config.yaml

Using a custom ConfigMap with the helm chart by providing the following values:
```
config:
create: false
```
The template that generates the Secret(cnpg-controller-manager-config) will not include `apiVersion` in the rendered output.
Attempting to deploy without a specified api version will give the following error message:
```
groupVersion shouldn't be empty
```

Generate correct Secret when using custom ConfigMap

---

charts/cloudnative-pg/values.yaml

My auditors want fully qualified container images, I figured others would probably benefit from this as well.

Drop obsolete test pod values

---

.github/dependabot.yml

Dependabot is just duplicating the work being done by Renovate, so we are disabling it.

chore: disable dependabot

---

charts/cloudnative-pg/templates/config.yaml
charts/cloudnative-pg/templates/deployment.yaml

Fixes https://github.com/cloudnative-pg/charts/issues/156
with `config.secret=false`:
```shell
$ helm template test --set config.secret=false charts/cloudnative-pg | grep cnpg-controller-manager-config -C 5
#
apiVersion: v1
kind: ConfigMap
metadata:
name: cnpg-controller-manager-config
labels:
helm.sh/chart: cloudnative-pg-0.19.0
app.kubernetes.io/name: cloudnative-pg
app.kubernetes.io/instance: test
app.kubernetes.io/version: "1.21.0"
--
spec:
containers:
- args:
- controller
- --leader-elect
- --config-map-name=cnpg-controller-manager-config
- --webhook-port=9443
command:
- /manager
env:
- name: OPERATOR_IMAGE_NAME
```
with `config.secret=true`:
```shell
$ helm template test --set config.secret=true charts/cloudnative-pg | grep cnpg-controller-manager-config -C 5
#
apiVersion: v1
kind: …
```

fix: avoid setting configmap name with config.secret=true

---

.github/workflows/release-publish.yml

This fixes a typo causing tags to not be correctly extracted when the name of the chart contains `-`.

Bug Fix: cosign step not correctly extracting tag version

---

charts/cluster/README.md
charts/cluster/templates/cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

Closes #206 
Added the postgresUID & GID from the [Clusterspec](https://cloudnative-pg.io/documentation/1.22/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec) to the helm template.

Added support for the specific user UID & GID

---

charts/cloudnative-pg/values.yaml

According to most used monitoring stack dashboard label value should be "1" to be automatically loaded by Grafana. While it's not very hard to find it took me some time to figure out why dashboard wasn't loaded.
https://github.com/prometheus-community/helm-charts/blob/e7b492f14f217bfa5616e36bf1eb031cae2721b1/charts/kube-prometheus-stack/values.yaml#L1032

Grafana dashboard label to "1"

---

.github/workflows/release-publish.yml

Hopefully this simple change in the `release-publish` workflow would resolve the following issue:
```
By typing 'y', you attest that (1) you are not submitting the personal data of any other person; and (2) you understand and agree to the statement and the Agreement terms at the URLs listed above.
Are you sure you would like to continue? [y/N] Error: signing [ghcr.io/cloudnative-pg/charts/cluster:0.0.3]: recursively signing: signing digest: should upload to tlog: user declined the prompt
main.go:74: error during command execution: signing [ghcr.io/cloudnative-pg/charts/cluster:0.0.3]: recursively signing: signing digest: should upload to tlog: user declined the prompt
Error: Process completed with exit code 1.
```

Bug Fix Attempt: Cosign confirmation prompt

---

charts/cluster/README.md
charts/cluster/templates/_backup.tpl
charts/cluster/values.schema.json
charts/cluster/values.yaml

This PR exposed the `backup.barmanObjectStore.wal` and `backup.barmanObjectStore.data` properties so that the encryption can be disabled.
This is needed in the case where you are using MinIO without encryption enabled. The defaults for encryption are still: `AES256`.
In addition the compression and parallelism properties are exposed for fine-tuning the storage space and performance of your cluster.
Closes: #198

feat(cluster): Exposed backup.barmanObjectStore.wal and backup.barmanObjectStore.data

---

.github/workflows/release-publish.yml

Additionally - using variables to pull the repository name instead of hard-coding it.

Bug Fix: Release process tried to sign prov files in addition to the chart file

---

.github/workflows/release-publish.yml

We need to add dependencies before running chart-releaser, see https://github.com/helm/chart-releaser/issues/135#issuecomment-915850640.

ci: properly add dependency before chart-releaser

---

charts/cluster/README.md
charts/cluster/templates/_barman_object_store.tpl
charts/cluster/templates/ca-bundle.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

This PR adds a chart values to `endpointCA` in both the backup and recovery sections, allowing a user to specify a private CA. The value is stored in a secret, which can either be created manually, or will be created automatically if the `create` option is true.
Resolves #229

Add config value endpointCA for private S3 such as MinIO

---

charts/cluster/README.md
charts/cluster/prometheus_rules/cluster-ha-critical.yaml
charts/cluster/prometheus_rules/cluster-ha-warning.yaml
charts/cluster/prometheus_rules/cluster-high_connection-critical.yaml
charts/cluster/prometheus_rules/cluster-high_connection-warning.yaml
charts/cluster/prometheus_rules/cluster-high_replication_lag.yaml
charts/cluster/prometheus_rules/cluster-instances_on_same_node.yaml
charts/cluster/prometheus_rules/cluster-low_disk_space-critical.yaml
charts/cluster/prometheus_rules/cluster-low_disk_space-warning.yaml
charts/cluster/prometheus_rules/cluster-offline.yaml
charts/cluster/prometheus_rules/cluster-zone_spread-warning.yaml
charts/cluster/templates/prometheus-rule.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

Adds the ability to disable specific PrometheusRules:
```yaml
cluster:
monitoring:
prometheusRule:
excludeRules: # NEW
- CNPGClusterHAWarning
- CNPGClusterZoneSpreadWarning
```
In the process I also restructured how Prometheus rules are generated so each one now has its own file.

Added the ability to exclude specific PrometheusRules

---

charts/cluster/README.md
charts/cluster/templates/_bootstrap.tpl
charts/cluster/values.yaml

Bug Fix: barmanObjectStore.serverName not initialized correctly preventing recovery when the cluster name is different.

Bug Fix: barmanObjectStore.serverName not initialized correctly

---

charts/cluster/prometheus_rules/cluster-ha-critical.yaml
charts/cluster/prometheus_rules/cluster-ha-warning.yaml
charts/cluster/prometheus_rules/cluster-high_connection-critical.yaml
charts/cluster/prometheus_rules/cluster-high_connection-warning.yaml
charts/cluster/prometheus_rules/cluster-high_replication_lag.yaml
charts/cluster/prometheus_rules/cluster-instances_on_same_node.yaml
charts/cluster/prometheus_rules/cluster-low_disk_space-critical.yaml
charts/cluster/prometheus_rules/cluster-low_disk_space-warning.yaml
charts/cluster/prometheus_rules/cluster-offline.yaml
charts/cluster/prometheus_rules/cluster-zone_spread-warning.yaml
charts/cluster/templates/prometheus-rule.yaml

The added labels allow you to better route alert events.

feat(cluster): Added additional PrometheusRule labels

---

charts/cluster/templates/_barman_object_store.tpl

Currently the cluster chart allows setting inheritFromAzureAD, but this is not propagated into the configuration.

bugfix(cluster): Propagate inheritFromAzureAD to the barman configuration

---

charts/cluster/README.md
charts/cluster/README.md.gotmpl

This add sandwiches the `Getting Started.md` file link in `<>` so that the space in the file is escaped, which will then render the link in the `README.md` when viewing on GitHub.

Update charts/cluster/README.md - fix Getting Started doc markdown link by escaping space

---

charts/cluster/README.md
charts/cluster/templates/cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

This makes it possible to configure roles using the chart by adding an array in `cluster.roles` in `values.yaml`. The content of the array are taken as is and used as `.spec.managed.roles.`
This is a follow up to PR #226, which ended up with conflicts, so I started a new one.
In this new PR I signed off my changes, and I ran `make schema docs`.
The rationale for adding the `with` inside instead of outside `managed:` in `cluster.yaml` is that in case it is needed at some point to bring other things into `managed`, we would have to put an `if` with several conditions outside, and several `ifs` inside in order to avoid the empty element. I did try the chart without specifying roles to check if the empty `managed` was a problem, and there was no problem.
Closes #201

feat(cluster): Make roles configurable

---

charts/cluster/prometheus_rules/cluster-high_connection-critical.yaml
charts/cluster/prometheus_rules/cluster-high_connection-warning.yaml
charts/cluster/prometheus_rules/cluster-high_replication_lag.yaml
charts/cluster/prometheus_rules/cluster-instances_on_same_node.yaml
charts/cluster/prometheus_rules/cluster-offline.yaml
charts/cluster/prometheus_rules/cluster-zone_spread-warning.yaml

Fixes the false positive `CNPGClusterOffline` alert reported in #283.
Additionally this improves the query performance by performing a direct match instead of a pattern match on `namespace`.
Closes: #283

fix(cluster): Prometheus Rule CNPGClusterOffline false positives

---

charts/cloudnative-pg/templates/deployment.yaml

There was a typo in deployment.yaml  additionalEnvVars -> additionalEnv  
I accidentally let this in there from using the web ide

fix additionalEnv typo in deployment.yaml

---

charts/cluster/templates/_barman_object_store.tpl
charts/cluster/templates/cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

The operator supports walStorage, but the chart does not (yet).  This PR fixes that.
In addition, this PR addresses issue https://github.com/cloudnative-pg/charts/issues/311 so gkeEnvironment can be set without the operator admission webhook rejecting the update.

Add walStorage capability and remove gkeEnvironment conflict in cluster chart.

---

charts/cloudnative-pg/templates/deployment.yaml
charts/cloudnative-pg/values.schema.json
charts/cloudnative-pg/values.yaml

When running in eks, the deployment is failing because of the webhook with the following error:
> Internal error occurred: failed calling webhook "mcluster.cnpg.io": failed to call webhook: Address is not allowed
The fix would be to set `hostNetwork` true but it is not configurable in the chart. 
In addition to that, the `dnsPolicy` needs to be set to `ClusterFirstWithHostNet` to give `hostNetwork` pods access to internal DNS.

chore: add support for `hostNetwork` in chart

---

.github/workflows/lint.yml

The Lint job doesn't run for PRs from outside, because the job is configured to only run on pushes to branches. This fixes that.

Bug Fix: lint-job not working

---

charts/cluster/templates/cluster.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

Fixes https://github.com/cloudnative-pg/charts/issues/366
Upgrading from cluster-v0.0.9 to cluster-v0.0.10 forces walStorage to enabled with no way to disable it.
This reverts to walStorage not being configured as in cluster-v0.0.9 unless `.Values.cluster.walStorage.enabled` is set to true.

Revert to walStorage disabled by default and add enabled flag to enable

---

charts/cluster/README.md
charts/cluster/templates/cluster.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster-assert.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
charts/cluster/test/timescale-minio-backup-restore/chainsaw-test.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

adding pg_ident and shared_preload_libraries similar to #321
@Stevenpc3 
Closes: #314
Closes: #342

exposing pg_ident and shared_preload_libraries

---

charts/cluster/examples/basic.yaml
charts/cluster/examples/pgbouncer.yaml
charts/cluster/examples/recovery-backup.yaml
charts/cluster/examples/recovery-object_store.yaml
charts/cluster/examples/recovery-pg_basebackup.yaml
charts/cluster/examples/standalone-s3.yaml
charts/cluster/test/monitoring/01-monitoring_cluster.yaml
charts/cluster/test/pooler/01-pooler_cluster.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
charts/cluster/test/postgresql-minio-backup-restore/01-standalone_cluster.yaml
charts/cluster/test/postgresql-minio-backup-restore/05-recovery_backup_cluster.yaml
charts/cluster/test/postgresql-minio-backup-restore/07-recovery_object_store_cluster.yaml
charts/cluster/test/postgresql-minio-backup-restore/09-recovery_backup_pitr_cluster.yaml
charts/cluster/test/postgresql-pg_basebackup/00-source-cluster.yaml
charts/cluster/test/postgresql-pg_basebackup/02-pg_basebackup-cluster.yaml

In a few tests, the `type: ` is not provided, defaulting to `postgresql`. If a new value is set as default in the `values.yaml` file, the tests fail. This ensures that this won't be the case anymore.

Add explicit `postgresql` in places where inferred by default `type`

---

charts/cluster/templates/cluster.yaml

Issue was because YAML output for this section of the cluster.yaml was
parameters:
parameters: {}
pg_hba: []
pg_indent: []
Whereas it should be
parameters: {}
pg_hba: {}
pg_indent: {}
but parameters is a helm keyword so it would consume all the keywords in the parameters step before pg_hba or pg_indent were called.
This simple re-ordering should fix the issue (and has for me in testing)
Closes: #408

Re-order template keywords

---

charts/cluster/README.md
charts/cluster/templates/cluster.yaml
charts/cluster/templates/pooler.yaml
charts/cluster/test/monitoring/01-monitoring_cluster-assert.yaml
charts/cluster/test/monitoring/01-monitoring_cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

Allow to customize resources as supported at https://cloudnative-pg.io/documentation/1.20/cloudnative-pg.v1/#postgresql-cnpg-io-v1-PoolerMonitoringConfiguration

feat(cluster): Extend monitoring options with relabelings

---

charts/cluster/templates/image-catalog-timescaledb-ha.yaml

Older images needed their corresponding versions too. Fixed typo in charts/cluster/templates/image-catalog-timescaledb-ha.yaml

Fixed versions typo in image-catalog-timescaledb-ha 

---

.github/actions/setup-kind/action.yml
.github/workflows/lint.yml
.github/workflows/release-publish.yml

An old version of helm is being used for the linter and inside the setup-kind reusable workflow.
This makes the linter fail with an error that's been already fixed in newer versions of helm:
```
==> Linting charts/cloudnative-pg
Error:  templates/podmonitor.yaml: object name must be between 0 and 253 characters: ""
```
Not sure why Renovate is not opening an automated PR for these files.. (maybe given that the helm version currently hardcoded is very old it can't find an upgrade path?!)

chore: bump helm to v3.16

---

charts/cluster/prometheus_rules/cluster-offline.yaml

Use `namespace/cluster` instead of `labels.job` which is not returned in the expression.
Fixes: #428

fix(cluster): correct CNPGClusterOffline rule description

---

CODEOWNERS

Adds Itay Grudev to the default CODEOWNERS rule, as per the governance document:
https://github.com/cloudnative-pg/governance/blob/main/COMPONENT-OWNERS.md#operator-chart

Adds Itay Grudev to the default list of CODEOWNERS

---

.github/actions/deploy-cluster/action.yml
.github/actions/deploy-operator/action.yml
.github/actions/verify-cluster-ready/action.yml
.github/workflows/tests-operator.yml
README.md
charts/cloudnative-pg/README.md
charts/cloudnative-pg/templates/NOTES.txt
charts/cloudnative-pg/templates/_helpers.tpl
charts/cloudnative-pg/templates/config.yaml
charts/cloudnative-pg/templates/deployment.yaml
charts/cloudnative-pg/templates/podmonitor.yaml
charts/cloudnative-pg/templates/rbac.yaml
charts/cloudnative-pg/values.schema.json
charts/cloudnative-pg/values.yaml

Add a way to deploy the operator in single-namespace mode, restricting the operator's capabilities to solely the namespace in which it has been installed.
Closes #435

feat: support cnpg operator namespace-restricted installation

---

charts/cluster/README.md
charts/cluster/templates/cluster.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster-assert.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

Adds serviceAccountTemplate to cluster configuration for IAM support

---

charts/cluster/templates/cluster.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster-assert.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
charts/cluster/values.yaml

Add support for enablePDB configuration option
Fix https://github.com/cloudnative-pg/charts/issues/395

feat(cluster): added support for enablePDB option

---

charts/cluster/templates/tests/ping.yaml

Fix #368 by adding `$PGDBNAME` env var to database-ping-test. 
Note that if the user uses a custom secret in the initdb, they will also need to add the dbname to the secret. 
I am happy to help in case of any missing changes for the fix.

add PGDBNAME to database-ping-test

---

charts/cluster/templates/scheduled-backups.yaml
charts/cluster/test/scheduledbackups/00-minio_cleanup-assert.yaml
charts/cluster/test/scheduledbackups/00-minio_cleanup.yaml
charts/cluster/test/scheduledbackups/01-scheduledbackups_cluster-assert.yaml
charts/cluster/test/scheduledbackups/01-scheduledbackups_cluster.yaml
charts/cluster/test/scheduledbackups/chainsaw-test.yaml

Fixes an issue introduced in #461 causing template evaluation to fail for ScheduledBackups.
This PR also adds a new test case specifically for `ScheduledBackups` so similar issues are caught.

Bug Fix: namespaceOverride template error in Scheduled Backups

---

charts/cloudnative-pg/templates/deployment.yaml

Instead of `{{- … }}`, the hyphen went to the end, i.e. `{{ … -}}`.
Therefore, `WATCH_NAMESPACE` is not set in the environment variables when `config.clusterWide: false`.

fix(cnpg): syntax error in deployment template prevents config.clusterWide from working

---

charts/cluster/test/scheduledbackups/chainsaw-test.yaml

Currently the scheduled backups test times out causing a test failure, simply because it take a bit longer to remove the backup objects.

Increased Scheduled Backups test cleanup timeout

---

charts/cluster/README.md
charts/cluster/templates/cluster.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster-assert.yaml
charts/cluster/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
charts/cluster/values.schema.json
charts/cluster/values.yaml

This PR adds the possibility to set the LDAP Configuration which is documented [here](https://cloudnative-pg.io/documentation/1.20/postgresql_conf/#ldap-configuration)
Same as in #409 without the merged service config feature.

feat(cluster): add ldap configuration and documentation

---

charts/cluster/README.md
charts/cluster/values.yaml

Corrected `definions` to `definitions`

docs: corrected spelling mistake

---

charts/cloudnative-pg/values.yaml

Updating the image can update the extensions available, but doesn't change the version installed in the database. We want to expose the info about an available update to the users.
These are the same changes included in
https://github.com/cloudnative-pg/cloudnative-pg/pull/7195

feat(metrics): check if extensions have updates

---

charts/cluster/README.md
charts/cluster/README.md.gotmpl

Looks like `cluster/docs/recovery.md` file was renamed to `cluster/docs/Recovery.md`, but `charts/cluster/README.md` still leads to old filename.

fix: dead readme link to `charts/cluster/docs/recovery.md`

---

.github/workflows/lint.yml
.github/workflows/release-pr.yml
.github/workflows/release-publish.yml
.github/workflows/tests-cluster-chainsaw.yaml
.github/workflows/tests-operator.yml

The permissions should be assigned on every job and by default should always be read
Closes #593

ci(security): set workflows permission to read-all by default

---

charts/cluster/templates/user-metrics.yaml
charts/cluster/test/monitoring/01-monitoring_cluster-assert.yaml
charts/cluster/test/monitoring/01-monitoring_cluster.yaml
charts/cluster/values.yaml

Adds support for:
* `cluster.monitoring.customQueries[].target_databases`
* `cluster.monitoring.customQueries[].predicate_query`
The `predicate_query` field is evaluated with `tpl` to allow users to specify more advanced configurations.

feat( cluster ): Advanced configuration for monitoring queries
